# This is a basic workflow to help you get started with Actions

name: R-CMD-check

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: 
      - master
      - devel
  pull_request:
    branches: 
      - master
      - devel
  schedule:
    - cron: '0 1 * * *'

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-18.04', 'macos-latest']
        include:
          - os: ubuntu-18.04
            cran: https://demo.rstudiopm.com/all/__linux__/bionic/latest
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      PIP_NO_WARN_SCRIPT_LOCATION: false
      RETICULATE_AUTOCONFIGURE: 'FALSE'
      CRAN: ${{ matrix.cran }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          cd sjSDM
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Install dependencies
        run: |
          cd sjSDM
          Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)" -e "remotes::install_cran('rcmdcheck')"
      - name: Install Python
        run: |
          cd sjSDM
          Rscript -e "remotes::install_github('rstudio/reticulate')" 
          Rscript -e "remotes::install_cran('devtools')"
      - name: Install PyTorch
        run: |
          cd sjSDM
          Rscript -e "remotes::install_local()"
          Rscript -e "sjSDM::install_sjSDM(env = 'r-reticulate')"
          Rscript -e "reticulate::conda_install(envname='r-reticulate', packages='pytest')"
          Rscript -e "reticulate::conda_install(envname='r-reticulate', packages='tqdm')"
      - name: tests ubuntu
        if: matrix.os == 'ubuntu-16.04'
        run: |
          cd sjSDM
          Rscript -e "Sys.setenv(RETICULATE_AUTOCONFIGURE = TRUE);try(Sys.setenv(RETICULATE_PYTHON = '/usr/share/miniconda/envs/r-reticulate/bin/python'));library(reticulate);try({torch = import('torch')});use_condaenv(condaenv = 'r-reticulate');library(sjSDM);py_config();try({testthat::test_dir('tests/testthat/')})"
      - name: tests windows
        if: matrix.os == 'windows-latest'
        run: |
          cd sjSDM
          Rscript -e "Sys.setenv(RETICULATE_AUTOCONFIGURE = TRUE);library(reticulate);try({torch = import('torch')});use_condaenv(condaenv = 'r-reticulate');library(sjSDM);py_config();install_diagnostic();try({testthat::test_dir('tests/testthat/')})"
      - name: tests macos
        if: matrix.os == 'macos-latest'
        run: |
          cd sjSDM
          Rscript -e "Sys.setenv(RETICULATE_AUTOCONFIGURE = TRUE);library(reticulate);try({torch = import('torch')});use_condaenv(condaenv = 'r-reticulate');library(sjSDM);py_config();install_diagnostic();try({testthat::test_dir('tests/testthat/')})"
      - name: Check
        continue-on-error: ${{ contains(matrix.allow_failure, 'true') }}
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(path = 'sjSDM/', args = '--no-manual', error_on = 'warning', check_dir = 'check')"
