# This is a basic workflow to help you get started with Actions

name: R-CMD-check

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: 
      - master
      - devel
  pull_request:
    branches: 
      - master
      - devel
  schedule:
    - cron: '0 1 * * *'

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-16.04', 'macos-latest']
        include:
          - os: ubuntu-16.04
            cran: https://demo.rstudiopm.com/all/__linux__/xenial/latest
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      PIP_NO_WARN_SCRIPT_LOCATION: false
      RETICULATE_AUTOCONFIGURE: 'FALSE'
      CRAN: ${{ matrix.cran }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          cd sjSDM
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Install dependencies
        run: |
          cd sjSDM
          Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)" -e "remotes::install_cran('rcmdcheck')"
      - name: Install Python
        run: |
          cd sjSDM
          Rscript -e "remotes::install_github('rstudio/reticulate')"
      - name: Install miniconda ubuntu
        if: matrix.os == 'ubuntu-16.04'
        run: |
          Rscript -e "reticulate::install_miniconda()"
      - name: Install miniconda windows
        if: matrix.os == 'windows-latest'
        run: |
          Rscript -e "reticulate::install_miniconda()"
      - name: Install miniconda mac
        if: matrix.os == 'macos-latest'
        run: |
          wget https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.2-MacOSX-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          hash -r
          rm miniconda.sh
          conda config --set auto_update_conda false
      - name: Install PyTorch
        run: |
          cd sjSDM
          Rscript -e "remotes::install_local()"
          Rscript -e "reticulate::conda_create('r-reticulate', packages = c('python==3.6.9'))"
          Rscript -e "sjSDM::install_sjSDM(env = 'r-reticulate')"
      - name: Check
        continue-on-error: ${{ contains(matrix.allow_failure, 'true') }}
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(path = 'sjSDM/', args = '--no-manual', error_on = 'warning', check_dir = 'check')"
